
server:
  port: 8080


spring:
    datasource:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: oracle.jdbc.driver.OracleDriver
#        url: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 130.36.193.72)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = 130.36.193.72)(PORT = 1521))(FAILOVER=ON)(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = orauz)(FAILOVER_MODE =(TYPE = SELECT)(METHOD = BASIC))))
#        username: YCC
#        password: YCC
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/Springboot
          username: root
          password: 123456789
    thymeleaf:
      cache: false
    devtools:
      remote:
        restart:
          enabled: true
      restart:
        additional-paths: src/main/java
        exclude: static/**,public/**



#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.unicom.bss.Model
  configuration:
    map-underscore-to-camel-case: true
#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

#restart.include.mapper=/mapper-[\\w-\\.]+jar
#restart.include.pagehelper=/pagehelper-[\\w-\\.]+jar
#spring.thymeleaf.cache=false
#spring.devtools.restart.enabled=true
#spring.devtools.restart.additional-paths=src/main/java
#spring.devtools.restart.exclude=static/**,public/**
