
server:
  port: 8080


spring:
    datasource:
#        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
          filters: stat
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/Springboot
          username: root
          password: 123456789
          initial-size: 1
          min-idle: 1
          max-active: 20
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
    thymeleaf:
      cache: false
    devtools:
      remote:
        restart:
          enabled: true
      restart:
        additional-paths: src/main/java
        exclude: static/**,public/**



#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.unicom.bss.Model
  configuration:
    map-underscore-to-camel-case: true
#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

#restart.include.mapper=/mapper-[\\w-\\.]+jar
#restart.include.pagehelper=/pagehelper-[\\w-\\.]+jar
#spring.thymeleaf.cache=false
#spring.devtools.restart.enabled=true
#spring.devtools.restart.additional-paths=src/main/java
#spring.devtools.restart.exclude=static/**,public/**
